export const TEACHER_LIST_REQUEST = "TEACHER_LIST_REQUEST";
export const TEACHER_LIST_SUCCESS = "TEACHER_LIST_SUCCESS";
export const TEACHER_LIST_FAIL = "TEACHER_LIST_FAIL";

export const TEACHER_DETAILS_REQUEST = "TEACHER_DETAILS_REQUEST";
export const TEACHER_DETAILS_SUCCESS = "TEACHER_DETAILS_SUCCESS";
export const TEACHER_DETAILS_FAIL = "TEACHER_DETAILS_FAIL";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
